version: '3'

networks:
  database:

services:
  shop:
    build:
      target: make_app
      context: .
      dockerfile: warehouse/Dockerfile
    networks:
      - database
    depends_on:
      - db
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - DATABASE_HOST=${DATABASE_HOST:-db}

  db_panel:
    image: dpage/pgadmin4
    networks:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=adelkhalitov1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Qwerty12345

  db:
    image: postgres:alpine
    networks:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Benq1234
      - POSTGRES_DB=web

  nginx:
    image: nginx:alpine
    ports:
      - '3005:80'
    networks:
      - database
    depends_on:
      - db_panel
      - shop
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
