export enum NamespaceEnum {
  AUTH_MAP = 'AUTH_MAP',
  //Database providers
  TRANSACTION_RUNNER = 'TRANSACTION_RUNNER',
  SESSION_SINGLETON = 'SESSION_SINGLETON',

  DEFAULT_ENTITY_MANAGER = 'DEFAULT_ENTITY_MANAGER',
}
