export class TimeUtil {
  static ONE_SECOND_IN_MILLISECONDS = 1000;
  static ONE_MINUTE_IN_MILLISECONDS = TimeUtil.ONE_SECOND_IN_MILLISECONDS * 60;
  static ONE_HOUR_IN_MILLISECONDS = TimeUtil.ONE_MINUTE_IN_MILLISECONDS * 60;
  static ONE_DAY_IN_MILLISECONDS = TimeUtil.ONE_HOUR_IN_MILLISECONDS * 24;
}
